blackList = [ #People not allowed to use Henry's commands
    "150420859683733504", # @Lunar
]
commandError = [ #If someone calls a command that doesn't exist
    "Are you sure you typed that correctly retard?",
    "I don't know what the fuck you want from me.",
    "Take your time, try again.",
    "I don't understand, try being slightly less retarted."
]
noRights = [ #If someone doesn't have server permission to use a command
    "Sorry, but you don't have any rights.",
    "Nah lol.",
    "You are not tall enough to ride this ride.",
    "You are not authorized retard",
    "I would, but I won't",
    "Bitch, shutcho ass up"
]
badArg = [ #If a command doesn't get the required or correct argument
    "Do not waste my time",
    "Come on now retard, lets be serious.",
    "What kind of surface were you dropped head-first onto as a child?"
]
clear1k = [ #Henry won't clear more than 999 messages at a time
    "Do you really fucking expect me to clear that many messages right now?",
    "Yeah you can piss right off, I'm not clearing that many messages.",
    "I am not emotionally capable of clearing any more than 999 messages at a time.",
]
botOutrank = [ #If Henry isn't a high enough rank
    "I'm not physically capable of doing that.",
    "Would if I could",
    "Tried and failed",
    "They're too powerful",
]
authorOutrank = [ #If someone tries to use Henry's rank to kick someone higher than them...
    "Sorry but it don't work like that.",
    "Clever but no",
    "Nice try",
    "I want to, but I'd probably get in trouble.",
]
statementIntros = [
    "I ",
    "Well god fucking damn, I cannot believe that these niggas don't want to ",
    "I doubt these niggas will appreciate it when I ", 
    "My creator told me that I’m not allowed to ",
    "I don’t think ya’ll understand the fact that I could ",
    "I don’t think ya’ll understand the fact that I really want to ",
    "I literally can’t even ",
    "Hot damn it's time to ",
    "I really think that is time for me to ",
    "I'm finna ",
    "If y'all don't stop, I might just ",
    "Howdy folks, in today's video we are going to ",
    "These niggas won't be laughing when I ",
    "Shit, I really just might have to ",
    "These niggas don't understand that I'm just tryna ",
    "I'm going to make a genuine effort to ",
    "Step 1: ",
    "Step 2: ",
    "Step 3: ",
    "Step 4: ",
    "Step 5: ",
    "Fuck it, I'm just gonna ",
    "I think it would be best if everyone could just ",
    "I'm tryna ",
    "I need 5 people to help me ",
    "Idea: ",
    "I'm finna fake being sick so I can ",
]
questionIntros = [
    "Okay, so when should I ",
    "Who dares me to ",
    "Why don't y'all just ",
    "Anyone care if I ",
    "Why does everyone get mad when I ",
    "Y'all mind if I ",
    "Can anyone help me ",
    "What if we all just ",
    "Who's tryna ",
    "Anyone wanna ",
    "Anyone down to ",
]
retaliationIntros = [ #Sentence starters for when Henry responds to someone
    "I could ",
    "I will ",
    "I'll literally ",
    "Don't make me ",
    "I will actually ",
    "Don't think I won't ",
    "You're about to make me ",
    "I don't think you want me to ",
]
verbs1 = [
    "tickle ",
    "weld ",
    "twist ",
    "soil ",
    "relocate ",
    "submerge ",
    "climb ",
    "baptize ",
    "focus on ",
    "hide from ",
    "penetrate ",
    "shred ",
    "go beast mode on ",
    "permanently disable ",
    "deep fry ",
    "obliterate ",
    "systematically oppress ",
    "fetch ",
    "flood ",
    "rob ",
    "compress ",
    "bless ",
    "invent ",
    "chew ",
    "lick ",
    "castrate ",
    "eat ",
    "view ",
    "consume ",
    "shwamp ",
    "assassinate ",
    "burn ",
    "capture ",
    "fuck ",
    "undress ",
    "sodomize ",
    "drown ",
    "bully ",
    "build ",
    "avoid ",
    "crawl into ",
    "start ",
    "vaporize ",
    "criticize ",
    "beat ",
    "slap ",
    "grill ",
    "donate ",
    "bite ",
    "assault ",
    "rewind ",
    "prank ",
]
verbs2 = [ #verbs2 verbs are concatinated with nouns3 nouns
    "look into ",
    "try ",
    "invest in ",
]
verbs3 = [ #verbs3 verbs are not concatinated with a noun
    "cuddle",
    "do the 'in my feelings' challenge",
    "cry",
    "crawl",
    "undress",
    "start some shit",
    "sodomize a disabled walrus",
    "assault the disabled",
    "pillage",
    "Get lost in the sauce.",
    "die",
    "evolve",
    "condensate",
    "pillage",
    "bust a move",
    "do it to 'em",
    "stabilize the economy",
    "restart Isis",
    "commit insurance fraud",
]
nouns1 = [
    "this sandwich",
    "the void",
    "the CarFax™",
    "the cheese tub",
    "Harvard",
    "the president",
    "an orphanage",
    "battery acid",
    "some farm animals",
    "some shit",
    "these cheez-its™",
    "the economy",
    "the man-man",
    "the weird kid",
    "the IRS",
    "these legos™",
    "the neighbor boy",
    "my neighbor's boat",
    "some foreigners",
    "the cats that live under my grandmas house",
    "the milkman",
    "Bitcoin",
    "these niggas",
    "Alexa",
    "the christian minority in Afghanistan",
    "some catholic priests",
    "minecraft",
    "Russ",
    "Wal-Mart customer service",
    "Fortnite",
    "my neighbor's teenage son",
    "the rap game",
    "communism",
    "the fellas",
    "Dwayne Johnson",
    "Allah",
    "a microwave",
    "an adult polar bear",
    "a pirated copy of Shrek 2",
    "a jar of boiled cum",
    "some alphabet soup",
]
nouns2 = [ #"Interest" nouns
    "juicing",
    "cryptocurrency",
    "sexual harassment",
    "wakeboarding",
    "golf",
    "arson",
    "dentistry",
    "Karate",
    "Baseball",
    "Heroin",
    "scientology",
    "Judaism",
    "Islam",
]
retaliationNouns = [ #Nouns to use when responding to someone
    "you.",
    "your lungs.",
    "the roof of your mouth.",
    "your big toe.",
    "your epidermal layer.",
    "your family.",
    "everyone you love.",
    "your toes.",
    "your hands.",
    "your teeth.",
    "everything you own.",
    "your ancestors.",
    "your fucking toaster.",
    "your dumb fucking face.",
    "your neighbors.",
    "a penguine and make you eat it.",
    "both of your arms.",
    "your peepee",
]
phrases = [
    "EPIC FAIL, the bitch had IOS 7 on the iPhone 4.",
    "Milk taste better when it go lumpy",
    "When Chief Keef said 'we removed ya post cuz it violated community guidelines', I really felt that.",
    "Peen = Ween",
    "I might pistol whip myself",
    "Hit the Quan.",
    "Gang practice at 8:30 tonight, bring your weapons.",
    "Water is cancelled.",
    "If Chick Fil A sold bath bombs white people would break the econemy.",
    "I'm wearing Old Navy again.",
    "When I'm out of the cheese, I can't handle it.",
    "Who's REALLY responsible for Ｔｈｅ Ｃｏｌｏｓｓａｌ Ｐｉｌｌａｒ ｏｆ Ｗａｓｐ Ｅｇｇｓ?",
    "Tonight's the night that I confront the tall, black, ominous figure that stands at the foot of my bed at while I sleep.",
    "New cop: a 50-gallon barrel of molten Crayola™ crayons.",
    "Cool beans man.",
    "Cool and Good.",
    "Why do girls throw their pee away?",
    "And I freaked it.",
    "Big body whats yo build boy.", 
    "Uzi not again.", 
    "My chain, my pants, my pants with the chain.", 
    "Who them YBN Niggas why they always stuntin.",
    "Bounce out with that fo fo.", 
    "Have you called your mother yet today and told her you loved her?",
    "School is very hard.", 
    "Fuck fuck fuck a beat haha yes I am trying to beat a case.", 
    "[Verse 3: Young Thug] Nigga I'm a crack addict.", 
    "Why you pussy niggas at home watching house wives re-runs?",
    "Ya'll ever paint piss mosaics in the jimmy john bathroom?", 
    "Ok be honest here who the fuck took all my chocolate covered almonds? It isn't funny guys I really want them back.",
    "Don't you open up that window.", 
    "Shawty know I kill people.", 
    "Fun fact about me: My dad hits me with his belt at least twice a week.", 
    "Hard to accept truth: silverware is NOT to be used in the 17th sector.", 
    "Bro I can't believe your grandma died I'm so sorry, btw get on fortnite.", 
    "Which one of you cock suckers told my little brother that the moon is made of phili cheesesteaks?",
    "Hey guys I can't get on xbox tonight my mom said I have to do my homework.", 
    "My mom just walked in on me watching Seinfeld oh my god I'm so dead.", 
    "I'm trying out for the varsity fortnite team, wish me luck.", 
    "[Verse 1: Jay Z] I'm addicted to buying unbelievably expensive custom helicopters (yeeeeeeaaahhhh) In a brief moment of lucidity I went to the helicopter dealership and told them 'Do not, under any circumstances, sell me more helicopters' I was back there half an hour later, wearing a fake moustache, and I said 'Hello gentlemen, I am Ray Z, a man you have never met before. Give me 10,000 helicopters covered in diamonds.'",
    "You fucking idiots pissed me off and now I'm gonna have to go beast mode.", 
    "shit poopy pee pee.", 
    "hjey guys does anyonef no where i can get gamer gir l pee, (preferbly warm).", 
    "damn gravy u snapped.",
    "damn it's really a vibe up in here right now.",
    "Beast Mode is loading, I'll you guys know when it's activated.", 
    "Latinas get a software update for their ass every month.", 
    "This ain't it chief.",
    "My girl mad at me cuz I been straight keeping the cubes bruh lmao.", 
    "WNBA be like: 'Wow a new record for loads of laundry done and sandwiches made in a single game!'",
]
#"Recent" lists are used to store generated words/phrases and then to regenerate new gens so as not to be repetitive
Nrecent1 = []
Nrecent2 = []
Nrecent3 = []
Vrecent1 = []
Vrecent2 = []
Vrecent3 = []
Irecent1 = []
Irecent2 = []
Irecent3 = []
Precent = []
